language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - PYTHONPATH='.'
branches:
  only:
    - master
install: 
  - /usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  - pip install . --use-mirrors
  - pip install nose
  - brew install node
  - curl http://npmjs.org/install.sh | sh
  - npm install zombie
script: 
  - nosetests --where=zombie
