language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - PYTHONPATH='.'
branches:
  only:
    - next
before_install:
  - npm update
  - npm cache clean
  - ~/virtualenvs/python2.7/bin/activate
  - npm install zombie
  - ~/virtualenvs/$TRAVIS_PYTHON_VERSION/bin/activate
install: 
  - pip install . --use-mirrors
  - pip install nose
  - pip install fudge
script: 
  - nosetests --where=zombie
