language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - PYTHONPATH='.'
branches:
  only:
    - next
before_install:
  - export TRAVIS_PYTHON_VERSION=2.7
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get install nodejs nodejs-dev npm
  - npm update
  - npm install zombie
install: 
  - export TRAVIS_PYTHON_VERSION=3.2
  - pip install . --use-mirrors
  - pip install nose
  - pip install fudge
script: 
  - nosetests --where=zombie
