language: python
python:
  - "2.6"
  - "2.7"
env:
  - PYTHONPATH='.'
branches:
  only:
    - next
before_install:
  - node -v
  - sudo apt-get install npm
  - npm update
  - npm cache clean
  - npm install zombie
install: 
  - pip install . --use-mirrors
  - pip install nose
  - pip install fudge
script: 
  - nosetests --where=zombie
